# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app_pb2 as app__pb2


class CacheStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Store = channel.unary_unary(
        '/rpc.Cache/Store',
        request_serializer=app__pb2.StoreReq.SerializeToString,
        response_deserializer=app__pb2.StoreResp.FromString,
        )
    self.Get = channel.unary_unary(
        '/rpc.Cache/Get',
        request_serializer=app__pb2.GetReq.SerializeToString,
        response_deserializer=app__pb2.GetResp.FromString,
        )


class CacheServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Store(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Store': grpc.unary_unary_rpc_method_handler(
          servicer.Store,
          request_deserializer=app__pb2.StoreReq.FromString,
          response_serializer=app__pb2.StoreResp.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=app__pb2.GetReq.FromString,
          response_serializer=app__pb2.GetResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpc.Cache', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AccountsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetByToken = channel.unary_unary(
        '/rpc.Accounts/GetByToken',
        request_serializer=app__pb2.GetByTokenReq.SerializeToString,
        response_deserializer=app__pb2.GetByTokenResp.FromString,
        )


class AccountsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetByToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetByToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetByToken,
          request_deserializer=app__pb2.GetByTokenReq.FromString,
          response_serializer=app__pb2.GetByTokenResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpc.Accounts', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
